### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by paluh**

### CODE REVIEW

**Comment by paluh** [comment]
@rightfold Could you also tag new version?

**Comment by safareli** [comment]
If we merge this I guess we should bump major version right?

What you think instead using version range like:
```
"purescript-quickcheck": "5.x - 6.x"
```
as in this case we can bump minor (I guess)?

**Comment by paluh** [comment]
Yeah, sure. I was not aware that it is possible. I'm offline for the next two weeks so I'm going to update this PR when I'm back.

**Comment by paluh** [comment]
@safareli version range for `purescript-quickcheck` works fine. Thanks for suggestion!

**Comment by safareli** [comment]
Thanks here is new version 
https://github.com/rightfold/purescript-quotient/releases/tag/v2.1.0

**Comment by safareli** [comment]
Looks like using such range is braking, for example I was not using quickcheck at all, and was depending on this lib using `^v2.0.0` as bower is dumb it installed 6.x of quickcheck and it caused build resolution issues. (if it bower was smart it could have guessed that 5.x is better version as it's compatible with other libs)

So I have removed that 2.1.0 release and please use new v3 version sorry if it caused any inconvenience on your side

**Pull request merged**
